# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cortado
  description: Consolidated RTAs (Red Team Automations)
  annotations:
    backstage.io/source-location: "url:https://github.com/elastic/cortado/"
    github.com/project-slug: "elastic/cortado"
    github.com/team-slug: "elastic/threat-research-and-detection-engineering"
    buildkite.com/project-slug: "elastic/cortado"

spec:
  type: service
  owner: group:threat-research-and-detection-engineering
  lifecycle: production
