name: RTA Bug Report
description: Report a bug in Cortado RTA code
title: "[RTA Bug] "
labels: ["bug", "Team: TRADE"]
assignees: []

body:
  - type: input
    id: rta_name
    attributes:
      label: RTA name
      description: "The name of the RTA"
      placeholder: "e.g., app_bundler_execution, automator_workflows, etc"

  - type: dropdown
    id: os_family
    attributes:
      label: OS family
      options:
      - Windows
      - macOS
      - Linux
      - other - explain

  - type: input
    id: os_version
    attributes:
      label: OS version
      description: "The version of the OS"
      placeholder: "e.g., Windows 10, macOS Big Sur, Ubuntu 20.04"

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is. Include any logs, errors, unexpected behavior, or system responses"
      placeholder: "Describe the bug..."

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Expected behavior..."

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Upload screenshots..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other context, explanations or references about the issue"
      placeholder: "Additional context..."
