name: Feature Request
description: Suggest an idea for Cortado
title: "[FR] "
labels: ["enhancement", "Team: TRADE"]
assignees: []
rojects: ["elastic/1268"]

body:
  - type: dropdown
    id: feature
    attributes:
      label: New feature
      options:
      - Core codebase - CLI, orchestration, validation, testing, lib, ci/cd, etc.
      - RTAs - new RTAs, RTA variants, etc.
      - other - explain

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: "Is your feature request related to a problem? Please describe it clearly and concisely. Ex. I'm always frustrated when [...]"
      placeholder: "Describe the problem..."

  - type: textarea
    id: desired_solution
    attributes:
      label: Desired Solution
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe the solution you want..."

  - type: textarea
    id: considered_alternatives
    attributes:
      label: Considered Alternatives
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Describe any alternatives you've considered..."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other context, explanations or references about the feature request here."
      placeholder: "Additional context, explanations, or references..."
