name: Code checks

on:
  pull_request:
    branches: [ "*" ]
    paths:
      - "*.py"
      - ".github/workflows/*"
      - "**/*.py"

jobs:
  linting:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: setup-python
        with:
          python-version: '3.15'
      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cached-poetry-dependencies
        with:
          path: ./.venv
          key: venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-full
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Create a virtual env
        run: python3 -m venv ./.venv
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Install dependencies
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
          poetry config installer.parallel false
          poetry install --with dev --all-extras
      - name: Lint
        run: |
          . .venv/bin/activate
          poetry run ruff check ./cortado
      - name: Pyright
        run: |
          . .venv/bin/activate
          poetry run pyright ./cortado

  license-header-check:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check Cortado files for a license header
        run: |
          bash ./scripts/check-license.sh ./cortado
          exit $?
      - name: Check test files for a license header
        run: |
          bash ./scripts/check-license.sh ./tests
          exit $?

  unit-tests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.15'
      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cached-poetry-dependencies
        with:
          path: ./.venv
          key: venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-full
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Create a virtual env
        run: python3 -m venv ./.venv
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Install dependencies
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
          poetry config installer.parallel false
          poetry install --with dev --all-extras
      - name: Run tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/

  dependency-check-for-minimal-package:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        id: setup-python
        with:
          python-version: '3.15'
      - name: Set up cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cached-poetry-dependencies
        with:
          path: ./.venv
          key: venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-min
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Create a virtual env
        run: python3 -m venv ./.venv
      - if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        name: Install dependencies
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
          poetry config installer.parallel false
          # Skipping extras to see if RTA CLI is still executable
          poetry install --with dev
      - name: Verify RTA CLI
        run: |
          . .venv/bin/activate
          cortado-run-rta test-rta
