name: Community

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Fetch ephemeral GitHub token
        id: fetch-ephemeral-token
        uses: elastic/ci-gh-actions/fetch-github-token@2feb1c6f5086cf8e06f61ef35e275abed3456f7b # v1.5.3
        with:
          vault-instance: "ci-prod"
          vault-role: "token-policy-4a57efea1929"

      - name: Check if member of elastic org
        uses: actions/github-script@v6
        id: membership
        with:
          github-token: ${{ steps.fetch-ephemeral-token.outputs.token }}
          result-encoding: string
          script: |

            try {
              const result = await github.rest.orgs.getMembershipForUser({
                 org: "elastic",
                 username: '${{ github.actor }}'
              })

              console.log(result?.data?.state)
              if (result?.data?.state == "active"){
                console.log("%s: detected as an active member of elastic org", '${{ github.actor }}')
                return "member";
              } else {
                console.log("%s: not detected as active member of elastic org", '${{ github.actor }}')
                return "notMember";
              }

            } catch (error) {
              return "notMember";
            }


      - name: Add label for community members
        uses: actions/github-script@v6
        if: ${{ steps.membership.outputs.result == 'notMember' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['community']
            })
